//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SQLMonitorServerInfoXML {
    
    private SQLMonitorServerInfoXMLStatCounter[] performanceStatsField;
    
    private string serverNameField;
    
    private string computerNamePhysicalNetBIOSField;
    
    private string editionField;
    
    private string oSVersionField;
    
    private string instanceNameField;
    
    private string machineNameField;
    
    private string productVersionField;
    
    private string productLevelField;
    
    private string licenseTypeField;
    
    private string buildClrVersionField;
    
    private string collationField;
    
    private System.DateTime resourceLastUpdateDateTimeField;
    
    private string resourceVersionField;
    
    private byte cPUCountField;
    
    private byte hyperThreadRatioField;
    
    private string affinityTypeField;
    
    private byte schedulerCountField;
    
    private byte maxDegreeOfParallelismField;
    
    private byte costThresholdOfParallelismField;
    
    private System.DateTime startTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("StatCounter", IsNullable=false)]
    public SQLMonitorServerInfoXMLStatCounter[] PerformanceStats {
        get {
            return this.performanceStatsField;
        }
        set {
            this.performanceStatsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ServerName {
        get {
            return this.serverNameField;
        }
        set {
            this.serverNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ComputerNamePhysicalNetBIOS {
        get {
            return this.computerNamePhysicalNetBIOSField;
        }
        set {
            this.computerNamePhysicalNetBIOSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Edition {
        get {
            return this.editionField;
        }
        set {
            this.editionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OSVersion {
        get {
            return this.oSVersionField;
        }
        set {
            this.oSVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string InstanceName {
        get {
            return this.instanceNameField;
        }
        set {
            this.instanceNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MachineName {
        get {
            return this.machineNameField;
        }
        set {
            this.machineNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductVersion {
        get {
            return this.productVersionField;
        }
        set {
            this.productVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductLevel {
        get {
            return this.productLevelField;
        }
        set {
            this.productLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LicenseType {
        get {
            return this.licenseTypeField;
        }
        set {
            this.licenseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BuildClrVersion {
        get {
            return this.buildClrVersionField;
        }
        set {
            this.buildClrVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Collation {
        get {
            return this.collationField;
        }
        set {
            this.collationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime ResourceLastUpdateDateTime {
        get {
            return this.resourceLastUpdateDateTimeField;
        }
        set {
            this.resourceLastUpdateDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResourceVersion {
        get {
            return this.resourceVersionField;
        }
        set {
            this.resourceVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte CPUCount {
        get {
            return this.cPUCountField;
        }
        set {
            this.cPUCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte HyperThreadRatio {
        get {
            return this.hyperThreadRatioField;
        }
        set {
            this.hyperThreadRatioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AffinityType {
        get {
            return this.affinityTypeField;
        }
        set {
            this.affinityTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte SchedulerCount {
        get {
            return this.schedulerCountField;
        }
        set {
            this.schedulerCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte MaxDegreeOfParallelism {
        get {
            return this.maxDegreeOfParallelismField;
        }
        set {
            this.maxDegreeOfParallelismField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte CostThresholdOfParallelism {
        get {
            return this.costThresholdOfParallelismField;
        }
        set {
            this.costThresholdOfParallelismField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime StartTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SQLMonitorServerInfoXMLStatCounter {
    
    private System.DateTime currentServerTimeField;
    
    private uint physicalMemoryKBField;
    
    private ulong virtualMemoryKBField;
    
    private uint totalMemoryUsedKBField;
    
    private uint targetMemoryKBField;
    
    private ushort databaseCacheMemoryKBField;
    
    private ushort freeMemoryKBField;
    
    private byte reservedServerMemoryKBField;
    
    private uint stolenServerMemoryKBField;
    
    private byte memoryGrantsOutstandingField;
    
    private byte memoryGrantsPendingField;
    
    private ushort batchRequestsSecField;
    
    private ushort sqlCompilationsSecField;
    
    private byte sqlReCompilationsSecField;
    
    private byte checkPointPagesSecField;
    
    private byte lockWaitsSecField;
    
    private decimal bufferCacheHitRatioField;
    
    private ushort pageLifeExpectancyField;
    
    private uint cPUBusyField;
    
    private uint cPUIdleField;
    
    private decimal cPUPercentageField;
    
    private ushort networkPacketsRecievedField;
    
    private ushort networkPacketsSendField;
    
    private byte networkPacketErrorsField;
    
    private ushort physicalIOTotalReadsField;
    
    private ushort physicalIOTotalWritesField;
    
    private byte physicalIOTotalErrorsField;
    
    private ushort physicalIOBusyField;
    
    private byte totalSessionsField;
    
    private byte totalUsersField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime CurrentServerTime {
        get {
            return this.currentServerTimeField;
        }
        set {
            this.currentServerTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint PhysicalMemoryKB {
        get {
            return this.physicalMemoryKBField;
        }
        set {
            this.physicalMemoryKBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong VirtualMemoryKB {
        get {
            return this.virtualMemoryKBField;
        }
        set {
            this.virtualMemoryKBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint TotalMemoryUsedKB {
        get {
            return this.totalMemoryUsedKBField;
        }
        set {
            this.totalMemoryUsedKBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint TargetMemoryKB {
        get {
            return this.targetMemoryKBField;
        }
        set {
            this.targetMemoryKBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort DatabaseCacheMemoryKB {
        get {
            return this.databaseCacheMemoryKBField;
        }
        set {
            this.databaseCacheMemoryKBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort FreeMemoryKB {
        get {
            return this.freeMemoryKBField;
        }
        set {
            this.freeMemoryKBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte ReservedServerMemoryKB {
        get {
            return this.reservedServerMemoryKBField;
        }
        set {
            this.reservedServerMemoryKBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint StolenServerMemoryKB {
        get {
            return this.stolenServerMemoryKBField;
        }
        set {
            this.stolenServerMemoryKBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte MemoryGrantsOutstanding {
        get {
            return this.memoryGrantsOutstandingField;
        }
        set {
            this.memoryGrantsOutstandingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte MemoryGrantsPending {
        get {
            return this.memoryGrantsPendingField;
        }
        set {
            this.memoryGrantsPendingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort BatchRequestsSec {
        get {
            return this.batchRequestsSecField;
        }
        set {
            this.batchRequestsSecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort SqlCompilationsSec {
        get {
            return this.sqlCompilationsSecField;
        }
        set {
            this.sqlCompilationsSecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte SqlReCompilationsSec {
        get {
            return this.sqlReCompilationsSecField;
        }
        set {
            this.sqlReCompilationsSecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte CheckPointPagesSec {
        get {
            return this.checkPointPagesSecField;
        }
        set {
            this.checkPointPagesSecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte LockWaitsSec {
        get {
            return this.lockWaitsSecField;
        }
        set {
            this.lockWaitsSecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal BufferCacheHitRatio {
        get {
            return this.bufferCacheHitRatioField;
        }
        set {
            this.bufferCacheHitRatioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort PageLifeExpectancy {
        get {
            return this.pageLifeExpectancyField;
        }
        set {
            this.pageLifeExpectancyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint CPUBusy {
        get {
            return this.cPUBusyField;
        }
        set {
            this.cPUBusyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint CPUIdle {
        get {
            return this.cPUIdleField;
        }
        set {
            this.cPUIdleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal CPUPercentage {
        get {
            return this.cPUPercentageField;
        }
        set {
            this.cPUPercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort NetworkPacketsRecieved {
        get {
            return this.networkPacketsRecievedField;
        }
        set {
            this.networkPacketsRecievedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort NetworkPacketsSend {
        get {
            return this.networkPacketsSendField;
        }
        set {
            this.networkPacketsSendField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte NetworkPacketErrors {
        get {
            return this.networkPacketErrorsField;
        }
        set {
            this.networkPacketErrorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort PhysicalIOTotalReads {
        get {
            return this.physicalIOTotalReadsField;
        }
        set {
            this.physicalIOTotalReadsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort PhysicalIOTotalWrites {
        get {
            return this.physicalIOTotalWritesField;
        }
        set {
            this.physicalIOTotalWritesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte PhysicalIOTotalErrors {
        get {
            return this.physicalIOTotalErrorsField;
        }
        set {
            this.physicalIOTotalErrorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort PhysicalIOBusy {
        get {
            return this.physicalIOBusyField;
        }
        set {
            this.physicalIOBusyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte TotalSessions {
        get {
            return this.totalSessionsField;
        }
        set {
            this.totalSessionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte TotalUsers {
        get {
            return this.totalUsersField;
        }
        set {
            this.totalUsersField = value;
        }
    }
}
